<script setup lang="ts">
import {computed,h,onMounted,ref,watch} from 'vue';
import {NButton,NCard,NCheckbox,NInput,NSelect,NImage,NTag,NModal,NPopconfirm,NAlert,useMessage,type DataTableColumns} from 'naive-ui';
import ViewportTable from '../components/ViewportTable.vue';
import {request} from '../api';
import {useAuthStore} from '../stores/auth';
interface Material{ID:number;Name:string;Path:string;CreatedAt:string}
const auth=useAuthStore(),message=useMessage(),items=ref<Material[]>([]),search=ref(''),location=ref<string|null>(null),checked=ref<number[]>([]),busy=ref(false),results=ref<string[]>([]),edit=ref<Material|null>(null),name=ref('');
const deleting=ref<number[]>([]);
async function deleteImages(){busy.value=true;results.value=[];try{const r=await request<{items:{id:number;deleted:boolean;error?:string}[]}>('/api/admin/materials/delete',{method:'POST',body:JSON.stringify({ids:deleting.value})});for(const item of r.items)results.value.push(`${items.value.find(i=>i.ID===item.id)?.Name||'图片'}：${item.deleted?'已删除':item.error}`);checked.value=checked.value.filter(id=>!r.items.some(i=>i.id===id&&i.deleted));deleting.value=[];await load()}catch(e){message.error(e instanceof Error?e.message:'删除失败')}finally{busy.value=false}}
async function copySelected(){try{await navigator.clipboard.writeText(items.value.filter(i=>checked.value.includes(i.ID)).map(i=>new URL(i.Path,window.location.origin).href).join('\n'));message.success('图片链接已复制')}catch{message.error('复制失败')}}
const filtered=computed(()=>items.value.filter(i=>(!search.value||i.Name.toLowerCase().includes(search.value.toLowerCase()))&&(!location.value||(i.Path.startsWith('/uploads/')?'local':'cloud')===location.value)));
watch([search,location],()=>checked.value=[]);
async function load(){try{items.value=(await request<{items:Material[]}>('/api/admin/materials')).items}catch(e){message.error(e instanceof Error?e.message:'读取失败')}}
onMounted(load);
async function rename(){if(!edit.value||!name.value.trim())return;busy.value=true;try{await request(`/api/admin/materials/${edit.value.ID}`,{method:'PUT',body:JSON.stringify({name:name.value})});edit.value=null;await load();message.success('名称已更新')}catch(e){message.error(e instanceof Error?e.message:'保存失败')}finally{busy.value=false}}
async function remove(){busy.value=true;try{await request('/api/admin/materials/remove',{method:'POST',body:JSON.stringify({ids:checked.value})});checked.value=[];await load();message.success('已移出素材库')}catch(e){message.error(e instanceof Error?e.message:'操作失败')}finally{busy.value=false}}
async function migrate(){busy.value=true;results.value=[];for(const item of items.value.filter(i=>checked.value.includes(i.ID)&&i.Path.startsWith('/uploads/'))){try{await request(`/api/admin/materials/${item.ID}/migrate`,{method:'POST'});results.value.push(`${item.Name}：已上传`)}catch(e){results.value.push(`${item.Name}：${e instanceof Error?e.message:'上传失败'}`)}}await load();busy.value=false}
async function upload(event:Event){const input=event.target as HTMLInputElement,files=Array.from(input.files||[]);if(!files.length)return;if(files.length>100){message.error('每批最多100张');input.value='';return}busy.value=true;results.value=[];for(const file of files){if(file.size>5*1024*1024){results.value.push(`${file.name}：超过5 MiB`);continue}try{const body=new FormData();body.append('file',file);await request('/api/admin/materials',{method:'POST',body});results.value.push(`${file.name}：已上传`)}catch(e){results.value.push(`${file.name}：${e instanceof Error?e.message:'上传失败'}`)}}input.value='';await load();busy.value=false}
async function copy(path:string){try{await navigator.clipboard.writeText(new URL(path,window.location.origin).href);message.success('地址已复制')}catch{message.error('复制失败')}}
const columns:DataTableColumns<Material>=[{type:'selection',width:40},{title:'预览',key:'image',width:80,render:i=>h(NImage,{src:i.Path,width:48,height:48,objectFit:'contain',alt:i.Name})},{title:'名称',key:'Name',width:220,ellipsis:{tooltip:true}},{title:'存储',key:'location',width:85,render:i=>h(NTag,{size:'small'},()=>i.Path.startsWith('/uploads/')?'本地':'云存储')},{title:'上传时间',key:'CreatedAt',width:150,render:i=>new Date(i.CreatedAt).toLocaleString('zh-CN')},{title:'操作',key:'actions',width:250,fixed:'right',render:i=>h('div',{style:'display:flex;gap:8px'},[h(NButton,{size:'small',onClick:()=>{edit.value=i;name.value=i.Name}},()=> '重命名'),h(NButton,{size:'small',onClick:()=>copy(i.Path)},()=> '复制图片链接'),h(NButton,{size:'small',type:'error',disabled:busy.value,onClick:()=>deleting.value=[i.ID]},()=> '删除')])}];
</script>
<template><NCard size="small"><template #header>素材库 <span class="muted">{{filtered.length}} 张</span></template><template #header-extra><label class="upload-button">{{busy?'正在处理…':'上传图片'}}<input type="file" multiple accept="image/png,image/jpeg,image/gif,image/webp" :disabled="busy" @change="upload"/></label></template>
<div class="toolbar"><NInput v-model:value="search" placeholder="搜索图片名称" clearable/><NSelect v-model:value="location" :options="[{label:'本地',value:'local'},{label:'云存储',value:'cloud'}]" placeholder="存储位置" clearable/><NButton @click="load">刷新</NButton></div>
<div v-if="checked.length" class="toolbar"><span>已选 {{checked.length}} 张</span><NButton size="small" @click="copySelected">复制图片链接</NButton><NButton size="small" type="error" :disabled="busy||checked.length>100" @click="deleting=[...checked]">删除图片</NButton><NButton size="small" @click="checked=filtered.map(i=>i.ID)">全选结果</NButton><NButton v-if="auth.isSuperAdmin" size="small" :loading="busy" @click="migrate">上传所选本地图片</NButton><NPopconfirm @positive-click="remove"><template #trigger><NButton size="small" type="error" :disabled="busy">移出素材库</NButton></template>所选图片将从素材库移除，已有访问地址仍可使用。</NPopconfirm><NButton size="small" @click="checked=[]">取消选择</NButton></div>
<div v-if="results.length" class="results" role="status"><p v-for="(r,i) in results" :key="i">{{r}}</p><NButton size="tiny" @click="results=[]">收起</NButton></div>
<ViewportTable :columns="columns" :data="filtered" :row-key="(i:Material)=>i.ID" v-model:checked-row-keys="checked" :pagination="{pageSize:20,showSizePicker:true,pageSizes:[10,20,50],pageSlot:3}" :scroll-x="825" :bordered="false" size="small"/>
<NModal :show="!!deleting.length" @update:show="v=>{if(!v&&!busy)deleting=[]}" preset="dialog" title="删除图片" :mask-closable="false" :closable="!busy">
将删除 {{deleting.length}} 张图片及其存储文件。引用这些图片的页面可能无法继续显示图片，CDN 缓存可能延迟更新。
<template #action><NButton :disabled="busy" @click="deleting=[]">取消</NButton><NButton type="error" :loading="busy" @click="deleteImages">确认删除</NButton></template></NModal>
<NModal :show="!!edit" @update:show="v=>{if(!v)edit=null}" preset="card" title="重命名图片" style="width:min(420px,94vw)"><NInput v-model:value="name" :maxlength="255" @keyup.enter="rename"/><template #footer><NButton type="primary" :loading="busy" :disabled="!name.trim()" @click="rename">保存</NButton></template></NModal>
</NCard></template>
<style scoped>.toolbar{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-bottom:12px}.toolbar .n-input{width:240px}.toolbar .n-select{width:140px}.upload-button{position:relative;background:#1677ff;color:white;padding:7px 12px;border-radius:6px;cursor:pointer;overflow:hidden}.upload-button input{position:absolute;inset:0;opacity:0;cursor:pointer;width:100%}.results{max-height:100px;overflow:auto;margin-bottom:10px;overflow-wrap:anywhere}@media(max-width:600px){.toolbar .n-input{width:100%}}</style>
